---
- hosts: personal
  roles:
    - basic
    - neovim
    - tmux
    - zsh
  vars:
    tmux_conf_local_src: files/.tmux.conf.local.personal
- hosts: servers
  roles:
    - basic
    - neovim
    - tmux
    - zsh
