---
- name: Update apt cache (Debian-family)
  apt:
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Install dependencies (Debian-family)
  package:
    name: "{{ zsh_dependencies }}"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Change shell to zsh (Debian-family)
  user:
    name: "{{ zsh_user }}"
    shell: "{{ zsh_shell }}"
  become: true
  when: ansible_os_family == "Debian"

- name: Clone oh-my-zsh to host
  git:
    repo: "{{ zsh_oh_my_zsh_repo }}"
    version: "{{ zsh_oh_my_zsh_version }}"
    dest: "{{ zsh_oh_my_zsh_dest }}"
    depth: 1

- name: Clone oh-my-zsh plugins to host
  git:
    repo: "https://github.com/{{ item.owner }}/{{ item.repo }}"
    version: master
    dest: "{{ zsh_plugin_dir }}/{{ item.repo }}"
  with_items: "{{ zsh_plugins }}"

- name: Link config files into home
  file:
    src: "{{ item }}"
    dest: "{{ zsh_config_dest }}{{ item | basename }}"
    state: link
    force: true
  loop: "{{ query('fileglob', role_path + '/files/.*') }}"
