---
- name: Update packages
  apt:
    update_cache: true

- name: Install dependencies
  package:
    name: "{{ zsh_dependencies }}"
    state: present
  become: true

- name: Change shell to zsh
  user:
    name: "{{ zsh_user }}"
    shell: "{{ zsh_shell }}"
  become: true

- name: Clone oh-my-zsh to host
  git:
    repo: "{{ zsh_oh_my_zsh_repo }}"
    version: "{{ zsh_oh_my_zsh_version }}"
    dest: "{{ zsh_oh_my_zsh_dest }}"
    depth: 1

- name: Clone oh-my-zsh plugins to host
  git:
    repo: "https://github.com/{{ item.owner }}/{{ item.repo }}"
    version: master
    dest: "{{ zsh_plugin_dir }}/{{ item.repo }}"
  with_items: "{{ zsh_plugins }}"

- name: Copy config files to host
  copy:
    src: "{{ item }}"
    dest: "{{ zsh_config_dest }}"
    owner: "{{ zsh_config_owner }}"
    group: "{{ zsh_config_group }}"
    mode: "{{ zsh_config_mode }}"
  with_fileglob: "{{ zsh_config_src }}"
