---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: "Get installed packages"
    package_facts:
      manager: auto
  
  - name: Verify git installed
    assert:
      that: "'{{ item }}' in ansible_facts.packages"
    loop:
      - git
      - gnupg2
      - neovim

  - name: Get directory status - neovim_config_dir
    stat:
      path: /home/root/.config/nvim
    register: neovim_config_dir_stat
  - name: Check directory exists - neovim_config_dir
    assert:
      that: neovim_config_dir_stat.stat.exists

  - name: Get directory status - vim-plug
    stat:
      path: /home/root/.local/share/nvim/site/autoload/plug.vim
    register: neovim_vim_plug_stat
  - name: Check directory exists - vim-plug
    assert:
      that: neovim_vim_plug_stat.stat.exists