---
- name: Update packages
  apt:
    update_cache: true

- name: Install Git
  package:
    name: "git"
    state: present
  become: true

- name: Install Tmux
  package:
    name: "{{ tmux_name }}"
    state: present
  become: true

- name: Check if folder exists
  stat:
    path: "{{ repo_dest }}"
  register: file_details

- name: Clone Tmux Config
  git:
    repo: "{{ repo_clone_url }}"
    dest: "{{ repo_dest }}"
    version: "{{ repo_version }}"
  when: not file_details.stat.exists

- name: Create symlink to .tmux.conf
  file:
    src: "{{ tmux_conf_src }}"
    dest: "{{ tmux_conf_dest }}"
    state: link

- name: Copy .tmux.conf.local
  copy:
    src: "{{ tmux_conf_src }}.local"
    dest: "{{ tmux_conf_dest }}.local"
    remote_src: yes