---
- name: Update packages
  apt:
    update_cache: true

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ neovim_dependencies }}"

- name: Install Neovim
  apt:
    name: "{{ neovim_name }}"
  become: true

- name: Create Neovim config folder
  file:
    path: "{{ neovim_config_dir }}"
    owner: "{{ neovim_config_owner }}"
    group: "{{ neovim_config_group }}"
    mode: "{{ neovim_config_mode }}"
    state: directory

- name: Place configuration file
  copy:
    src: "{{ neovim_file_src }}"
    dest: "{{ neovim_file_dest }}"
    owner: "{{ neovim_file_owner }}"
    group: "{{ neovim_file_group }}"
    mode: "{{ neovim_file_mode }}"

- name: Create Neovim config folder
  file:
    path: "{{ neovim_plugin_dir }}"
    owner: "{{ neovim_plugin_owner }}"
    group: "{{ neovim_plugin_group }}"
    mode: "{{ neovim_plugin_mode }}"
    state: directory

- name: Download vim-plug
  get_url:
    url: "{{ neovim_plug_url }}"
    dest: "{{ neovim_plug_dest }}"
    owner: "{{ neovim_plug_owner }}"
    group: "{{ neovim_plug_group }}"
    mode: "{{ neovim_plug_mode }}"

- name: Install plugins
  command: nvim -c PlugInstall -c q -c q
  changed_when: false
