name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test all roles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run test
        run: make test