name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test all roles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          DEBIAN_INTERACTIVE=noninteractive
          sudo apt update && \
          sudo apt install python3-pip -y && \
          pip3 install molecule molecule-docker pytest
      - name: Run test
        run: make test